### ISSUE TITLE
Aurora AudioLink

### ISSUE THREAD

**Issue by lilrad** [PiMaker/VRChatUnityThings#1]
The aurora works fine alone, as soon as you tick "AudioLink Support" it becomes an error material. Currently audio link is working correctly within the world before this. Any advice?

**Comment by lilrad** [comment]
![image](https://user-images.githubusercontent.com/74993906/145694805-1627c249-fcbe-4141-aa16-df6e063e1680.png)

**Comment by PiMaker** [comment]
Sorry, that was already fixed in 7ad04ae801, but evidently I forgot to update the Unity package. Should be fixed in 8e3c613e54 now (re-download `Aurora.unitypackage` and just import it over the existing one in your project). Thanks for the notice!

**Comment by lilrad** [comment]
awesome thankyou
