### ISSUE TITLE
Audiolink VPM package leads to the aurora shader unable to find the AudioLink.cginc file

### ISSUE THREAD

**Issue by Ikbenmathijs** [PiMaker/VRChatUnityThings#2]
The new path for AudioLink.cginc with the VPM version is "../../../Packages/com.llealloo.audiolink/Runtime/Shaders/AudioLink.cginc", instead of the old "../../AudioLink/Shaders/AudioLink.cginc" currently used in the shader

**Comment by PiMaker** [comment]
You need to use the AudioLink shader upgrader, it should work without issues. See here: https://github.com/llealloo/vrc-udon-audio-link/blob/master/FAQ.md#question-2

**Comment by Ikbenmathijs** [comment]
oh didn't know there was an upgrader, I just modified the file myself, but just made the issue so it could be fixed for other people
